### ISSUE TITLE
REMOVE FRONTEND REDUNDANCIES 

### ISSUE THREAD

**Issue by smartens-bit** [denartha10/comp30830-flask-application#54]
-Remove redundant features: 
-Remove places libraries, not necessary for project 
-Remove autocomplete for searches, not necessary 
-Remove temporary placeholders 
-Fix live clock (use LocaleTimeString to get your display date instead of creating through variables)

**Comment by Southwick-Adam** [comment]
Simon your last push covered this can I close the issue?

**Comment by Southwick-Adam** [comment]
I see that this should have been closed with the last push. Closing.
